apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      serviceAccountName: master
      containers:
      - name: web-app
        image: andrstp/master:1.0
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: config
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000